theme = "catppuccin_mocha"

[editor]
line-number = "relative"
cursorline = true
color-modes = true
true-color = true

[editor.file-picker]
hidden = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[editor.lsp]
auto-signature-help = false
display-messages = true
display-inlay-hints = true

[editor.statusline]
left = ["mode", "file-type",  "file-encoding" , "version-control"] 
center = ["spinner","file-name", "file-modification-indicator"]
right = [
    "selections",
    "primary-selection-length",
    "position",
    "total-line-numbers"
    "spacer",
    "diagnostics",
    "workspace-diagnostics",
]
separator = "|"

[keys.normal.space]
i = ":toggle lsp.display-inlay-hints"

[keys.normal]
"." = "repeat_last_motion"
